### PR TITLE
Removed node_modules, updated .gitignore, and added package.json

### PR DESCRIPTION
**Pull request by jonathanmtran**

### CODE REVIEW

**Comment by slavaaaaaaaaaa** [comment]
2844 files changed
who do you think you is

image

**Comment by slavaaaaaaaaaa** [comment]
need the whole crew on this one for reviews

**Comment by asciifaceman** [comment]
Here at OrcaLLC, we commit our dependencies because NPM is a fucking pile of trash

**Comment by asciifaceman** [comment]
@jonathanmtran I'm honestly going to reject this because it is one giant commit making it impossible to actually see what is being done entirely. 

If you can break out your additions and removals into different commits I might actually consider it

**Comment by jonathanmtran** [comment]
You got it!

**Comment by asciifaceman** [comment]
Last thing @jonathanmtran  - It still works right? I can't check right now on my machine ©️ but it just seems you lifted deps into npm package lock and cleaned node_modules out - I just want to make sure our software actually runs - poorly or not

**Comment by asciifaceman** [comment]
Also upon merge you will be promoted to Org member.

Congratulations, Jr. Jave Engineer (JJE) 

We look forward to the contributions you will bring to the future of technology.

**Comment by jonathanmtran** [comment]
> It still works right?

Of course. It works on my box :tm:

screenshot from 2018-10-12 14-13-27

**Review by asciifaceman — APPROVED** [review]

**Comment by slavaaaaaaaaaa** [comment]
u gaise are gr8

**Pull request merged**
